---
# compat for amazon linux
- set_fact: ansible_distribution_major_version=6
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"
  tags: ['php']

- set_fact: ansible_distribution_major_version=7
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  tags: ['php']


- name: merge php defaults with override values
  set_fact: _php_config="{{ php_default_config|combine(php_config|default({})) }}"
  tags: ['php']

- name: install ius repo package
  yum: name=https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm state=present lock_timeout=180
  tags: ['php']

- name: install ius rpm gpg key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-{{ ansible_distribution_major_version }}
  tags: ['php']

- name: install php packages
  yum: name="{{ php_packages }}" state=present lock_timeout=180
  tags: ['php']

- name: place php.ini
  template: src=etc.php.ini.j2 dest=/etc/php.ini owner=root group=root mode=0640
  notify:
    - reload httpd
    - reload php-fpm
  tags: ['php']

- name: install php-fpm
  yum: name={{ php_fpm_package }} state=present lock_timeout=180
  when: php_use_fpm == true
  tags: ['php']

# The RPM installs a www.conf that we don't want
- name: remove rpm-provided php-fpm site config
  copy: dest=/etc/php-fpm.d/www.conf owner=root group=root mode=0644 content=""
  when: php_use_fpm == true
  tags: ['php']

- name: place php-fpm base configuration
  template: src=etc.php-fpm.conf.j2 dest=/etc/php-fpm.conf mode=0644 owner=root group=root
  when: php_use_fpm == true
  notify: reload php-fpm
  tags: ['php']

- name: place php-fpm site configuration
  template: src=etc.php-fpm.d.sites.conf.j2 dest=/etc/php-fpm.d/sites.conf mode=0644 owner=root group=root
  when: php_use_fpm == true
  notify: reload php-fpm
  tags: ['php']

- name: start php-fpm
  service: name=php-fpm state=started enabled=true
  when: php_use_fpm == true
  tags: ['php']
