---
- name: reload php-fpm
  service: name=php-fpm state=reloaded
  when: php_use_fpm

- name: restart php-fpm
  service: name=php-fpm state=restarted
  when: php_use_fpm

- name: reload httpd
  service: name=httpd state=reloaded
  when: not php_use_fpm
